version: '2'
services:
  local:
    container_name: local
    build: .
    volumes:
      - .:/app
      - gradle_cache:/root/.gradle
    ports:
      - "8080:8080"
    environment:
      DB_HOST: db
      DB_USER: kevin
      DB_PASSWORD: password
      DB_PORT: 9001
    command: ["bash"]
    stdin_open: true
    depends_on:
      - db
  db:
    image: blacklabelops/hsqldb
    container_name: hsqldb
    ports:
     - "9001:9001"
    volumes:
      - /opt/database
    environment:
      HSQLDB_TRACE: 'true'
      HSQLDB_SILENT: 'false'
      HSQLDB_REMOTE: 'true'
      HSQLDB_DATABASE_NAME: 'hsqldb'
      HSQLDB_DATABASE_ALIAS: 'test'
      HSQLDB_DATABASE_HOST: 'localhost'
      HSQLDB_USER: 'kevin'
      HSQLDB_PASSWORD: 'password'
    labels:
      com.blacklabelops.description: "HSQL Development System"
      com.blacklabelops.service: "hsqldb-server"
volumes:
  gradle_cache:
