version: '2'
services:
  local:
    container_name: local
    build: .
    volumes:
      - .:/app
      - gradle_cache:/root/.gradle
    ports:
      - "8080:8080"
    environment:
      DB_HOST: db
      DB_USER: kevin
      DB_PASSWORD: password
      DB_PORT: 9001
      DB_TABLE: test
    command: ["bash"]
    stdin_open: true
volumes:
  gradle_cache:
